// <auto-generated />
using System;
using EFCoreBlogFeatures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreBlogFeatures.SQLite.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20250623184443_initialCreateBlogComments")]
    partial class initialCreateBlogComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("EFCoreBlogFeatures.Dto.BlogComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<Guid>("BlogPostUmbracoKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("blogPostUmbracoKey");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.ToTable("blogComment", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
